/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import type { DataClient } from '@microsoft/power-apps/data';
import { getClient } from '@microsoft/power-apps/data';
import { getDataSourcesInfo } from './data-source-info-generator';
import type { TableToTypescriptMapping } from './table-mapping-types';
import type { IAppGenDataClient, IOperationOptions, TableRow } from './types';

export class AppGenByocDataClient implements IAppGenDataClient {
    private byocSdkClient: DataClient;
    public constructor() {
        this.byocSdkClient = getClient(getDataSourcesInfo());
    }

    public async createRecordAsync(tableMetadata: TableToTypescriptMapping, record: TableRow): Promise<void> {
        const clientResult = await this.byocSdkClient.createRecordAsync<TableRow, TableRow>(tableMetadata.apiDataTableId, record);
        if (!clientResult.success) {
            throw new Error(JSON.stringify(clientResult.error || {}));
        }
    }

    public async updateRecordAsync(tableMetadata: TableToTypescriptMapping, record: TableRow, recordId: string): Promise<void> {
        const clientResult = await this.byocSdkClient.updateRecordAsync<TableRow, TableRow>(tableMetadata.apiDataTableId, recordId, record);
        if (!clientResult.success) {
            throw new Error(JSON.stringify(clientResult.error || {}));
        }
    }

    public async deleteRecordAsync(tableMetadata: TableToTypescriptMapping, recordId: string): Promise<void> {
        const clientResult = await this.byocSdkClient.deleteRecordAsync(tableMetadata.apiDataTableId, recordId);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-member-access
        if ((clientResult.data as any)?.[0]?.status !== 204) {
            throw new Error(JSON.stringify(clientResult.error || {}));
        }
    }

    public async retrieveRecordAsync(tableMetadata: TableToTypescriptMapping, recordId: string): Promise<TableRow> {
        const clientResult = await this.byocSdkClient.retrieveRecordAsync<TableRow>(tableMetadata.apiDataTableId, recordId, undefined);
        if (!clientResult.success) {
            throw new Error(JSON.stringify(clientResult.error || {}));
        }
        return clientResult.data;
    }

    public async retrieveMultipleRecordsAsync(tableMetadata: TableToTypescriptMapping, options?: IOperationOptions): Promise<TableRow[]> {
        const clientResult = await this.byocSdkClient.retrieveMultipleRecordsAsync<TableRow>(tableMetadata.apiDataTableId, options);
        if (!clientResult.success) {
            throw new Error(JSON.stringify(clientResult.error || {}));
        }
        return clientResult.data;
    }

    public requiresFullRowForUpdate(): boolean {
        return false;
    }
}
