/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { dataverseDataSourceOperations } from '../dataverse/dataverse-data-source-operations';
import { inMemoryDataSourceOperations } from '../in-memory/in-memory-data-source-operations';
import { localDataSourceOperations } from '../local/local-data-source-operations';
import type { CommonDataSourceOperations } from './common-data-source-operations';
import { getDataModelConfig } from './data-model-config-accessor';
import type { DataSourceType, TableToTypescriptMapping } from './table-mapping-types';

export const commonDataSourceOperations: Record<DataSourceType, CommonDataSourceOperations> = {
    ['InMemory']: inMemoryDataSourceOperations,
    ['Dataverse']: dataverseDataSourceOperations,
};

export function getCommonDataSourceOperations(tableMetadata: TableToTypescriptMapping): CommonDataSourceOperations {
    const dataModelConfig = getDataModelConfig();
    if (dataModelConfig.useLocalData || (typeof window !== 'undefined' && new URLSearchParams(window?.location.search).get('useLocalData') === 'true')) {
        return localDataSourceOperations;
    }

    const operations = commonDataSourceOperations[tableMetadata.dataSourceType];
    if (!operations) {
        throw new Error(`No CommonDataSourceOperations found for data source type: ${tableMetadata.dataSourceType}`);
    }
    return operations;
}
